language: node_js
node_js:
- '12.22.8'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # REGISTRY_TOKEN(editor=cozy, app=ascoresante)
  - secure: c6FyvonDlWewpcpeYps8wbTLVNU2lBOVWLB9pCSIXBBd4/KCGe8hpDFf4Rl1YveK5y4XGKYdbOw9+d3mU8XW8Cj5sIYJyNc3lEEZ3mVLIhndh5Z9etANTOKRyrz18zrH5FI5atsqbXMH7czziShZhixmJXIRaIWawyqTq6/qzduk7kGNKmkKs5dVHSUKXd5T30Uxv3EGkQLL0xiWiYub4iu7XvQ21yIB/Ty3EDfFhEoVUDcGZTKy8E81LyYB+v/StFFlQeDbW9ILVTrMgOoU6wLfIIUW8VwlIzoFdr7lwPw/UBGUuoHYH0Qp/Hc+E5HpDutHFARAdudybdLbnAfY4GYHXx3sdT3Yxs5/dW4UzHLX6DDION+Q5d2TaO2KCY6ndYPq+Hl0BDKgyzifNDROxzE+Rh8cfYMVyrnEtqVIEsfajG5vJddp39spobBFW7FcBnCiUfNtxj+T848tVBUE35r3Zc+tHMsl2x1qt0n9PKN+IhOaVn0jYf84Ll1zJUbMVKL/EhhbGMCJbaQ4ola4E3e6SDS5eaVoJe9x5m42qS/v1GHpo6jJ9SujUmMXbr744UOPfods1+LfSfs27kkmklKkM9vosjLbbtNO/AofrbHU8hBHdpm+fM5sLO2z06O6PzbXY3AFnnQnn1UyACNQBaeI3oubnZJCuePgpacXB1Y=
  # MATTERMOST_HOOK_URL
  - secure: P9AjcfAGo2fbKaNaUmhFW3ZwDbHpYXiyoBYCjvzJWYLOfS/yeIXjtePckjhzgteLjnytCXqPdLHcx/dGmkRFsEFbZVb5rYE+WCO8OOMOExwLh3ezj5xNOqtHSHDGg395CZn1FaKNJY48XSLTRJs6NfEdF+pqDM9A7RVb1iYTmf8D+8wnRCob5tz77ouefWQ149zXpN2HobM7fkxuW7E8ZqXAgp+5R73uHPaHHhnUNZhQ+sfRWVuWiaeE+tG5/L+GJugYxR9jydofR2WHHYeNyVOXK8kAOKI1RdndwQFa3YPXP8HH3KSHxa/NCt13OfN0ImLcCoYsmgqDRI+7BK7XzOpvPhj/gqQXJOuIR8hCGc2hr9WnxqkGPdGNIvwCKbzQXra+SwdvkrOJbvJPI31+554roVhwS8vHf9d/LwI/Tjl50il2KBiEBWdiARk7zE0McuYs4YEHBpyUmGLBzBkQDpk+v09edFNVo/2HA/+AdCUbH4/vwxFwast25IIEqz+lhkGlyX7+cUicjMAlAFdJkEN+SW7mO7nX9iyA0d52Z2nG7wotLnJkjRnCzuU+dJLESMfScOSsYpper9L4JTPAxxObvRpBXkU+Rt4TNj+fCY9j2j7gXGRBBXiWzYxcOJdI61bgP5K2gVcGRNf1lF4/hoLsdzrPT86sZghosNTvloc=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_5963eef8afc0_key -iv $encrypted_5963eef8afc0_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
